package com.myorg.lsf.outbox.admin;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

class JdbcOutboxAdminRepositoryTest {

    private JdbcTemplate jdbc;
    private JdbcOutboxAdminRepository repository;

    @BeforeEach
    void setUp() {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:outbox-" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        this.jdbc = new JdbcTemplate(dataSource);
        this.repository = new JdbcOutboxAdminRepository(new NamedParameterJdbcTemplate(dataSource), jdbc, "lsf_outbox");

        jdbc.execute("""
                CREATE TABLE lsf_outbox (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    topic VARCHAR(255) NOT NULL,
                    msg_key VARCHAR(255),
                    event_id VARCHAR(255) NOT NULL,
                    event_type VARCHAR(255),
                    correlation_id VARCHAR(255),
                    aggregate_id VARCHAR(255),
                    status VARCHAR(32) NOT NULL,
                    created_at TIMESTAMP NOT NULL,
                    sent_at TIMESTAMP NULL,
                    retry_count INT NOT NULL,
                    last_error VARCHAR(4000),
                    lease_owner VARCHAR(255),
                    lease_until TIMESTAMP NULL,
                    next_attempt_at TIMESTAMP NULL
                )
                """);
    }

    @Test
    void shouldListRowsByFiltersAndOrderNewestFirst() {
        insertRow("orders", "key-1", "evt-1", "orders.created.v1", "corr-1", "agg-1", "SENT", Instant.parse("2026-04-06T10:00:00Z"), 0, null, null, null, Instant.parse("2026-04-06T10:01:00Z"));
        insertRow("orders", "key-2", "evt-2", "orders.failed.v1", "corr-2", "agg-2", "FAILED", Instant.parse("2026-04-06T11:00:00Z"), 3, "boom", "node-a", Instant.parse("2026-04-06T11:05:00Z"), Instant.parse("2026-04-06T11:10:00Z"));
        insertRow("payments", "key-3", "evt-3", "payments.failed.v1", "corr-3", "agg-3", "FAILED", Instant.parse("2026-04-06T12:00:00Z"), 1, "boom", null, null, null);

        List<OutboxAdminRow> rows = repository.list(
                List.of(OutboxStatus.FAILED),
                "orders",
                "key-2",
                "orders.failed.v1",
                "corr-2",
                Instant.parse("2026-04-06T10:30:00Z"),
                Instant.parse("2026-04-06T11:30:00Z"),
                10,
                0
        );

        assertThat(rows).hasSize(1);
        OutboxAdminRow row = rows.getFirst();
        assertThat(row.eventId()).isEqualTo("evt-2");
        assertThat(row.correlationId()).isEqualTo("corr-2");
        assertThat(row.aggregateId()).isEqualTo("agg-2");
        assertThat(row.status()).isEqualTo(OutboxStatus.FAILED);
        assertThat(row.retryCount()).isEqualTo(3);
        assertThat(row.leaseOwner()).isEqualTo("node-a");
    }

    @Test
    void shouldRequeueByEventIdResetRetryAndClearLeaseState() {
        insertRow("orders", "key-2", "evt-2", "orders.failed.v1", "corr-2", "agg-2", "FAILED", Instant.parse("2026-04-06T11:00:00Z"), 5, "boom", "node-a", Instant.parse("2026-04-06T11:05:00Z"), Instant.parse("2026-04-06T11:10:00Z"));
        Instant now = Instant.parse("2026-04-06T12:30:00Z");

        int updated = repository.requeueByEventId("evt-2", OutboxStatus.RETRY, true, now);

        assertThat(updated).isEqualTo(1);
        OutboxAdminRow row = repository.findByEventId("evt-2").orElseThrow();
        assertThat(row.status()).isEqualTo(OutboxStatus.RETRY);
        assertThat(row.retryCount()).isZero();
        assertThat(row.lastError()).isNull();
        assertThat(row.leaseOwner()).isNull();
        assertThat(row.leaseUntil()).isNull();
        assertThat(row.nextAttemptAt()).isEqualTo(now);
    }

    @Test
    void shouldRequeueFailedRowsRespectLimitAndSupportMarkFailedAndDelete() {
        insertRow("orders", "key-1", "evt-1", "orders.failed.v1", "corr-1", "agg-1", "FAILED", Instant.parse("2026-04-06T10:00:00Z"), 2, "old", "node-a", Instant.parse("2026-04-06T10:05:00Z"), Instant.parse("2026-04-06T10:06:00Z"));
        insertRow("orders", "key-2", "evt-2", "orders.failed.v1", "corr-2", "agg-2", "FAILED", Instant.parse("2026-04-06T10:10:00Z"), 4, "old", "node-b", Instant.parse("2026-04-06T10:15:00Z"), Instant.parse("2026-04-06T10:16:00Z"));

        int updated = repository.requeueFailed(1, false, Instant.parse("2026-04-06T13:00:00Z"));

        assertThat(updated).isEqualTo(1);
        assertThat(repository.findByEventId("evt-1").orElseThrow().status()).isEqualTo(OutboxStatus.RETRY);
        assertThat(repository.findByEventId("evt-1").orElseThrow().retryCount()).isEqualTo(2);
        assertThat(repository.findByEventId("evt-2").orElseThrow().status()).isEqualTo(OutboxStatus.FAILED);

        int marked = repository.markFailedByEventId("evt-1", "x".repeat(3000));
        assertThat(marked).isEqualTo(1);
        OutboxAdminRow failedRow = repository.findByEventId("evt-1").orElseThrow();
        assertThat(failedRow.status()).isEqualTo(OutboxStatus.FAILED);
        assertThat(failedRow.lastError()).hasSize(2000);
        assertThat(failedRow.leaseOwner()).isNull();
        assertThat(failedRow.leaseUntil()).isNull();

        int deleted = repository.deleteByEventId("evt-1");
        assertThat(deleted).isEqualTo(1);
        assertThat(repository.findByEventId("evt-1")).isEmpty();
    }

    private void insertRow(String topic,
                           String msgKey,
                           String eventId,
                           String eventType,
                           String correlationId,
                           String aggregateId,
                           String status,
                           Instant createdAt,
                           int retryCount,
                           String lastError,
                           String leaseOwner,
                           Instant leaseUntil,
                           Instant nextAttemptAt) {
        jdbc.update("""
                        INSERT INTO lsf_outbox (
                            topic, msg_key, event_id, event_type, correlation_id, aggregate_id, status,
                            created_at, sent_at, retry_count, last_error,
                            lease_owner, lease_until, next_attempt_at
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                topic,
                msgKey,
                eventId,
                eventType,
                correlationId,
                aggregateId,
                status,
                Timestamp.from(createdAt),
                null,
                retryCount,
                lastError,
                leaseOwner,
                leaseUntil == null ? null : Timestamp.from(leaseUntil),
                nextAttemptAt == null ? null : Timestamp.from(nextAttemptAt)
        );
    }
}
